# Generated by Django 5.0.7 on 2024-07-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='My_User',
        ),
        migrations.AddField(
            model_name='permission',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='len',
            field=models.IntegerField(default=200),
        ),
    ]
