# Generated by Django 5.0.7 on 2024-07-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_rename_user_my_user_permission_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='my_user',
            name='password',
        ),
        migrations.AddField(
            model_name='my_user',
            name='tsz',
            field=models.IntegerField(default=0),
        ),
    ]
