# Generated by Django 5.0.7 on 2024-07-28 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_remove_my_user_email_remove_my_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_user',
            name='tsz',
            field=models.IntegerField(default=0, unique=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
