# Generated by Django 5.0.7 on 2024-07-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_remove_my_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_user',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='got_permission_at',
            field=models.DateField(),
        ),
    ]
