# Generated by Django 5.0.7 on 2024-07-30 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0006_remove_my_user_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_user',
            name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('user', 'permission')},
        ),
    ]
